[changelog]
header = ""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
protect_breaking_commits = true
tag_pattern = '^v[0-9]+\.[0-9]+\.[0-9]+$'
commit_parsers = [
  { field = "breaking", pattern = "true", group = "Breaking Changes" },
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Fixes" },
  { message = "^perf", group = "Performance" },
  { message = ".*", skip = true },
]

[bump]
initial_tag = "v0.1.0"
features_always_bump_minor = true
breaking_always_bump_major = true
